language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       - mm-common
       #- cluttermm
       #- libglademm

compiler:
  - gcc
  - clang

before_script:
  - echo "Broken so skip" # ./install-cluttermm.sh

script:
  - make
