language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       - mm-common
       #- cluttermm
       #- libglademm

compiler:
  - gcc
  - clang

before_script:
  - wget https://github.com/GNOME/cluttermm/archive/master.zip -O /tmp/cluttermm.zip
  - unzip /tmp/cluttermm.zip
  - pushd cluttermm-master
  - ./autogen.sh
  - ./configure --disable-documentation
  - make
  - popd

script:
  - make
