language: cpp
dist: trusty
sudo: true

env:
  - PKG_CONFIG_PATH=${HOME}/.local/share/pkgconfig:${HOME}/.local/lib/pkgconfig/ ACLOCAL_PATH="${HOME}/.local/share/aclocal"

addons:
  apt:
    sources:
       - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
       - ubuntu-toolchain-r-test # gcc-5 / g++-5
    packages:
       - atkmm-1.6
       - clutter-1.0
       - cmake
       - cmake-data
       - cpanminus
       - g++-5
       - gcc-5
       - gobject-introspection
       - gtk-doc-tools
       - libclutter-1.0-dev
       - libcogl-dev
       - libgtkmm-3.0-dev
       - libxml-parser-perl
       - mm-common
       - pangomm-1.4
       - uuid
       - uuid-dev

         #before_install:
         #  - sudo cpanm XML::XPath

compiler:
  - gcc
  - clang

before_script:
  - export CC=gcc-5
  - export CXX=g++-5
  - export CXXFLAGS=-Wno-deprecated-declarations
  - ./install-mm-common.sh 
  - ./install-cluttermm.sh 1.3.2
  - ./install-clutter-gtk.sh 1.5.2
  - ./install-clutter-gtkmm.sh CLUTTER_GTKMM_0_91_8
  - export PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig:${HOME}/.local/share/pkgconfig"
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/lib"

script:
  - cmake .
  - make
