language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       #- mm-common
       #- cluttermm
       - libgtkmm-2.4-dev

compiler:
  - gcc
  - clang

before_script:
  - ./install-mm-common.sh
  - ./install-cluttermm.sh
  - export PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig:${HOME}/.local/share/pkgconfig"
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/lib"

script:
  - cmake .
  - make
