language: cpp
sudo: false

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       - mm-common
       #- cluttermm
       #- libglademm

compiler:
  - gcc
  - clang

script:
  - make
