language: cpp
dist: trusty
sudo: false

env:
  - PKG_CONFIG_PATH=${HOME}/.local/share/pkgconfig:${HOME}/.local/lib/pkgconfig/ ACLOCAL_PATH="${HOME}/.local/share/aclocal"

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test # g++-5
    packages:
       - clang-3.9
       - cmake
       - g++-5
       - gtk-doc-tools
       - libclutter-1.0-dev
       - libgtkmm-3.0-dev
       - libxml-parser-perl
       - mm-common
       - uuid-dev

compiler:
  - gcc
  - clang

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - export CXXFLAGS="-Wno-deprecated-declarations"
  - ./deps/install-from-github.sh GNOME cluttermm 1.3.2 -p cluttermm-1.3.2-cairo-texture-namespace-fix.patch
  - ./deps/install-from-github.sh GNOME clutter-gtk 1.5.2
  - ./deps/install-from-github.sh GNOME clutter-gtkmm CLUTTER_GTKMM_0_91_8

script:
  - cmake .
  - make
