language: cpp
dist: trusty
sudo: false

env:
  global:
    - ACLOCAL_PATH="${HOME}/.local/share/aclocal"
    - PKG_CONFIG_PATH=${HOME}/.local/share/pkgconfig:${HOME}/.local/lib/pkgconfig/
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "d7P1GZ9wBDnNO/HuEMWwvT83iOaKt1vGvTeHBQ7hKzZerIUMMOQazStQd2vXKD3QqgRPFDXVtGNtAbFUp8EpaWX9ttsf/6UnksddVtMu62/OctI6lLWEle0f5FLlT3og85BSxydfpkYizinJd9I/xuUal/Sq2xb7qwUWp/ftmm6ffwwLMD2EqdzH8xOqY2xAe6Ex1U0TEeZJLnomgBmho0xNiXK3BPGXtSf+UUpCcn9j6VGvb/VCjgs6aF8LoJgr91wzg3ycuRrjbsP6G+WMpjy09ypFx5tLyHkjtyY7j+ES8eAcw7QEvLvMQh4IrmSajM7gSlTstiT5zidz88j6fCIpHTu+FMbjMrKEfZYlBcb9SPTXsEB57puhhs/+m2qTwa9dsPvCgmrwWRZ8lgr9UFH3QXeiqLmV22o3t3R4/VuS8zHKiROSVxlntz86EbphO8VxPcMxgdBxEME/zSchj567FPlDGiHZwjPShv7CW68pSs4YBklbMowUqJohkeDJc/NhK8edqEhkHA/Oh7qAOixPNHJuvyloOxzWrxyT4mUO6e1uvUrMZl+Q3Z4G32ZwgjH3Sv3Fl4fdSsi3x+b2Wi4VGRkW0HyXvB1Jtx1kVz3CfFr4e1+S2wQ0gG7/3NnHKKNfoZjHKzf0qEMjU+WmiECtwHHfj+WB4e+dcdgsCA4="

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test # g++-5
    packages:
      - clang-3.9
      - cmake
      - g++-5
      - gtk-doc-tools
      - libclutter-1.0-dev
      - libgtkmm-3.0-dev
      - libxml-parser-perl
      - mm-common
      - uuid-dev
  coverity_scan:
    project:
      name: "Griffon26/vhde"
      description: "VHDL Diagram Editor"
    notification_email: griffon26@kfk4ever.com
    build_command_prepend: cov-configure --comptype gcc --compiler g++-5 --template
    build_command: make
    branch_pattern: coverity_scan

compiler:
  - gcc
  - clang

before_install:
  # Exit now if we're not on the coverity_scan branch or not on the first travis job
  - test "${TRAVIS_BRANCH}" == "coverity_scan" -a "${TRAVIS_JOB_NUMBER##*.}" != 1 && exit 0

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - export CXXFLAGS="-Wno-deprecated-declarations -Wno-deprecated-register"
  - ./deps/install-from-github.sh GNOME cluttermm 1.3.2 -p cluttermm-1.3.2-cairo-texture-namespace-fix.patch
  - ./deps/install-from-github.sh GNOME clutter-gtk 1.5.2
  - ./deps/install-from-github.sh GNOME clutter-gtkmm CLUTTER_GTKMM_0_91_8
  - cmake .

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make; else cat "${HOME}/build/Griffon26/vhde/cov-int/scm_log.txt"; fi

